### ISSUE TITLE
Break the code into functions and use POST data for setting the request

### ISSUE THREAD

**Issue by chamathpali** [99xt/24sevenoffice-php-adapter#6]

**Comment by chamathpali** [comment]
Get the   values from a post request
         $company["companies"][0]['Name'] ="FROM EARNSHARK";
          $company["companies"][0]['Type'] ="Business";
          $company["companies"][0]['OrganizationNumber'] ="EARNSHARK ID";
          $company["companies"][0]['EmailAddresses']["Invoice"]["Value"] = "EMAIL";
          $company["companies"][0]['EmailAddresses']["Invoice"]["Name"] = "EMAIL";
          $company["companies"][0]['EmailAddresses']["Invoice"]["Description"] = "EMAIL";
          $company["companies"][0]['EmailAddresses']["Work"]["Value"] = "EMAIL";
          $company["companies"][0]['EmailAddresses']["Work"]["Name"] = "EMAIL";
          $company["companies"][0]['EmailAddresses']["Work"]["Description"] = "EMAIL";

**Comment by rehrumesh** [comment]
@chamathpali this issue can be closed?
